version: '3'
services:
    cf_builder:
        build: ./dockerfile/builder
        volumes:
            - /dev/bus/usb:/dev/bus/usb
        privileged: true
    cf_client:
        build: ./dockerfile/client
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /dev:/dev
        privileged: true
        ports:
            - 1189:1189/tcp
            - 1189:1189/udp
        environment:
            DISPLAY: unix:0
    cf_agent:
        build: ./dockerfile/agent
        volumes:
            - /dev:/dev
        network_mode: "host"
        privileged: true
        depends_on:
            - cf_client
    cf_translator:
        build: ./dockerfile/translator
        network_mode: "host"
    cf_rviz:
        build: ./dockerfile/rviz
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
        environment:
            DISPLAY: unix:0
        network_mode: "host"
        depends_on:
            - cf_translator
    cf_gcs:
        build: ./dockerfile/gcs
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
        environment:
            DISPLAY: unix:0
        network_mode: "host"
    cf_visualizer:
        build: ./dockerfile/visualizer
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
        environment:
            DISPLAY: unix:0
        network_mode: "host"